//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bs.XML.SpreadSheet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bs.XML.SpreadSheet.Resources.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &quot;{0}&quot; not represent valid column name..
        /// </summary>
        internal static string ColumnNameWrong {
            get {
                return ResourceManager.GetString("ColumnNameWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is missing a sheet named &quot;{1}&quot;..
        /// </summary>
        internal static string MissingSheetInFile {
            get {
                return ResourceManager.GetString("MissingSheetInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section SheetData not found.
        /// </summary>
        internal static string SheetDataNotFound {
            get {
                return ResourceManager.GetString("SheetDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet &quot;{0}&quot; not found..
        /// </summary>
        internal static string SheetNameNotFound {
            get {
                return ResourceManager.GetString("SheetNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file &quot;{0}&quot; not found..
        /// </summary>
        internal static string TemplateFileNameNotFound {
            get {
                return ResourceManager.GetString("TemplateFileNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file not found..
        /// </summary>
        internal static string TemplateFileNotFound {
            get {
                return ResourceManager.GetString("TemplateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heading &quot;{0}&quot; is duplicated in the title bar..
        /// </summary>
        internal static string TheHeadingIsDuplicated {
            get {
                return ResourceManager.GetString("TheHeadingIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sheet &quot;{0}&quot; must contain a header row..
        /// </summary>
        internal static string TheSheetMustContainHeaderRow {
            get {
                return ResourceManager.GetString("TheSheetMustContainHeaderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sheet &quot;{0}&quot; must contain at least three lines: a header line, a note line, and data lines..
        /// </summary>
        internal static string TheSheetMustContainThreeLines {
            get {
                return ResourceManager.GetString("TheSheetMustContainThreeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; out of Titles.
        /// </summary>
        internal static string TitleNotFound {
            get {
                return ResourceManager.GetString("TitleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string length in a cell must not exceed {0} characters..
        /// </summary>
        internal static string TooLongCellName {
            get {
                return ResourceManager.GetString("TooLongCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook has not any sheet..
        /// </summary>
        internal static string WorkbookHasNotAnySheet {
            get {
                return ResourceManager.GetString("WorkbookHasNotAnySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XlsxResource not loaded..
        /// </summary>
        internal static string XlsxResourceNotLoaded {
            get {
                return ResourceManager.GetString("XlsxResourceNotLoaded", resourceCulture);
            }
        }
    }
}
